### ISSUE TITLE
"Contribute to this page" commit break the build

### ISSUE THREAD

**Issue by kavi87** [seedstack/website#36]
After fixing minor typo on the website, the build failed. Currently the website is down because of this.

**Comment by adrienlauer** [comment]
7753e04 should fix this by using a fork of Hugo with its master fixed to 0.14 tag. 2dc869d should prevent the website from being updated if generation goes wrong.

**Comment by adrienlauer** [comment]
We should get a binary of Hugo instead of using go get though.

**Comment by pith** [comment]
agreed. It will certainly boost the build (if needed ^^).
