### ISSUE TITLE
Seedstack web site html link 404 Error

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/website#65]
_From @evinel on July 20, 2016 15:33_

On the security page : http://seedstack.org/docs/seed/manual/security/
the link <a href="/addons/ldap">LDAP add-on documentation</a> redirects to "404 page not found"

_Copied from original issue: seedstack/seedstack#12_

**Comment by adrienlauer** [comment]
This is because we are lacking documentation for the LDAP add-on.
@ydautremay should have written it a year ago or so but we have nothing so far. Maybe he could do something if he still remembers it. 

See seedstack/ldap-addon#2

**Comment by ydautremay** [comment]
My bad I guess. I'll see if I can do something about it.

**Comment by adrienlauer** [comment]
Fixed
