### ISSUE TITLE
Expand testing section with the features introduced on the latest releases

### ISSUE THREAD

**Issue by Sherpard** [seedstack/website#75]
Right now, Testing section lacks info about some major capabilities that the stack provides, such as @KerpelParameters, @ConfigurationProfies.... and such.

Having them on the the guide would be helpful

**Comment by adrienlauer** [comment]
This is now documented here: http://seedstack.org/docs/core/testing/#testing-features

**Comment by Sherpard** [comment]
Great! Thank you @adrienlauer :) It will be handy for sure
